apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.webhook.prod-webhook: |
    url: http://rollout-events-eventsource-svc.argo-events.svc.cluster.local:12000/rollout-success
    method: POST
    headers:
    - name: Content-Type
      value: application/json
  template.prod-webhook-template: |
    webhook:
      prod-webhook:
        method: POST
        body: |
          {
            "message": "Rollout Succeeded",
            "app": "{{app.metadata.name}}"
          }
  trigger.on-rollout-completed: |
    - send: [prod-webhook-template]
