apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  template.prod-webhook-template: |
    webhook:
      prod-webhook:
        method: POST
        body: |
          {
            "message": "Rollout Succeeded",
            "app": "{{app.metadata.name}}"
          }
  trigger.prod-webhook-trigger: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [prod-webhook-template]
