apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.webhook.prod-webhook: |
    url: http://argo-events-svc.argo-events.svc.cluster.local:12000
    method: POST
    headers:
    - name: Content-Type
      value: application/json
