apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: git-event-source
  namespace: argo-events
spec:
  eventBusName: default
  github:
    release-readiness:
      owner: jahnavibavuluri
      repository: go-test-app
      webhook:
        endpoint: /push
        port: "12001"
        method: POST
      events:
        - "*"
      filter:
        expression: |
          any(body.commits, {any(#.modified, { # == "jlp-cluster/rollout.yaml" })})
      insecure: true
      active: true
      contentType: json 
