apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: rollout-events
  namespace: argo-events
spec:
  eventBusName: default
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    rollout-success:
      endpoint: /rollout-success
      method: POST
      port: "12000"
