apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: release-readiness-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: git-dep
      eventSourceName: git-event-source
      eventName: release-readiness
  triggers:
    - template:
        name: trigger-release-readiness-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: git-triggered-release-readiness-workflow-
              spec:
                entrypoint: rr-checks  # Ensure this matches the template name
                templates:
                  - name: rr-checks
                    retryStrategy:
                      limit: "3"
                    steps:
                      - - name: rr-check-1
                          template: rr-check
                          arguments:
                            parameters:
                              - name: url
                                value: "https://www.google.com"
                      - - name: rr-check-2
                          template: rr-check
                          arguments:
                            parameters:
                              - name: url
                                value: "https://www.jetbrains.com/teamcity"
                  - name: rr-check
                    inputs:
                      parameters:
                        - name: url
                    container:
                      image: curlimages/curl
                      command: ["/bin/sh", "-c"]
                      args: ["curl -s -o /dev/null -w \"%{http_code}\" {{inputs.parameters.url}} | grep 200"]
