apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rollout-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: rollout-dep
      eventSourceName: rollout-events
      eventName: rollout-success
  triggers:
    - template:
        name: trigger-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: update-rollout-
              spec:
                entrypoint: update-image
                volumes:
                  - name: ssh-key-volume
                    secret:
                      secretName: github-ssh-key
                      items:
                        - key: ssh-privatekey
                          path: id_ed25519
                templates:
                  - name: update-image
                    script:
                      image: alpine/git
                      command: ["/bin/sh"]
                      volumeMounts:
                        - name: ssh-key-volume
                          mountPath: /root/.ssh
                      source: |
                        set -e

                        echo "Cloning the Git repository..."
                        # Clone the repository
                        GIT_SSH_COMMAND="ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no" git clone git@github.com:jahnavibavuluri/go-test-app.git
                        
                        cd go-test-app

                        echo "Extracting the image from jlp-cluster/rollout.yaml..."
                        # Extract the image from jlp-cluster/rollout.yaml
                        IMAGE=$(grep 'image:' jlp-cluster/rollout.yaml | awk '{print $2}')

                        echo "Updating the image in prod-cluster/rollout.yaml..."
                        # Update the image in prod-cluster/rollout.yaml
                        sed -i "s|image: .*|image: $IMAGE|" prod-cluster/rollout.yaml

                        echo "Configuring Git user..."
                        # Commit and push changes
                        git config --global user.email "jbavuluri@gmail.com"
                        git config --global user.name "jahnavibavuluri"

                        echo "Committing changes..."
                        git add prod-cluster/rollout.yaml
                        git commit -m "Update image in prod-cluster/rollout.yaml to $IMAGE"

                        echo "Pushing changes to repository"
                        GIT_SSH_COMMAND="ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no" git push origin main

                        echo "Workflow completed successfully!"
