apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rollout-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: rollout-dep
      eventSourceName: rollout-events
      eventName: rollout-success
  triggers:
    - template:
        name: trigger-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: simple-test-workflow
              spec:
                entrypoint: main
                templates:
                - name: main
                  container:
                    image: alpine
                    command: ["/bin/sh", "-c"]
                    args: ["echo 'workflow triggered successfully'"]
