apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: release-readiness-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: git-dep
      eventSourceName: git-event-source
      eventName: release-readiness
  triggers:
    - template:
        name: trigger-release-readiness-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: git-triggered-release-readiness-workflow-
              spec:
                entrypoint: rr-checks  
                templates:
                  - name: rr-checks
                    retryStrategy:
                      limit: "2"
                    steps:
                      - - name: rr-check-1
                          template: rr-check
                          arguments:
                            parameters:
                              - name: url
                                value: "https://396e-144-212-5-9.ngrok-free.app/test"
                        - name: rr-check-2
                          template: rr-check
                          arguments:
                            parameters:
                              - name: url
                                value: "https://github.com"
                      - - name: argo-sync
                          template: argo-cd-sync
                      - - name: argo-rollout-status-check
                          template: argo-rollout-status
                  - name: rr-check
                    inputs:
                      parameters:
                        - name: url
                    container:
                      image: curlimages/curl
                      command: ["/bin/sh", "-c"]
                      args: ["curl -s -o /dev/null -w \"%{http_code}\" {{inputs.parameters.url}} | grep 200"]
                  - name: argo-cd-sync
                    container:
                      image: argoproj/argocd:latest
                      command: ["/bin/sh", "-c"]
                      args:
                        - |
                          argocd login argocd-server.argocd.svc --username admin --password dXZIZ5isRj5IIPcJ --insecure
                          argocd app sync toolboxes-jlp-cluster
                  - name: argo-rollout-status
                    container:
                      image: jbavuluri/argo-rollouts-custom-image:latest
                      command: ["/bin/sh", "-c"]
                      args:
                        - |
                          # Install curl
                          # apt-get update && apt-get install -y curl

                          # Download Argo Rollouts CLI
                          #curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64 && \
                          #chmod +x ./kubectl-argo-rollouts-linux-amd64 && \
                          #mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts

                          echo "Waiting for the rollout to start progressing..."
                          until kubectl argo rollouts status go-test-app-jlp --namespace default | grep "Progressing"; do
                            sleep 5
                          done
                          echo "Rollout is progressing..."

                          echo "Waiting for rollout to become healthy..."
                          until kubectl argo rollouts status go-test-app-jlp --namespace default | grep "Healthy"; do
                            sleep 5
                          done
                          echo "Rollout is healthy"
