apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-test-workflow
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo 'Workflow triggered successfully!'"]
