apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-test-app
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
  selector:
    matchLabels:
      app: go-test-app
  template:
    metadata:
      labels:
        app: go-test-app
    spec:
      containers:
      - name: go-test-app
        image: jbavuluri/go-test-app:2.3
        ports:
        - containerPort: 8080
