apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-test-app
  template:
    metadata:
      labels:
        app: go-test-app
    spec:
      containers:
      - name: go-test-app
        image: jbavuluri/go-test-app
        ports:
        - containerPort: 8080
