apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rollout-success-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: rollout-success
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: trigger-kind-deployment
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: applications
          operation: update
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: toolboxes-kind
                namespace: argocd
              spec:
                syncPolicy:
                  automated:
                    prune: true
                    selfHeal: true
