apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-test-app
  namespace: default
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
  selector:
    matchLabels:
      app: go-test-app
  template:
    metadata:
      labels:
        app: go-test-app
    spec:
      containers:
      - name: go-test-app
        image: jbavuluri/go-test-app:2.5
        ports:
        - containerPort: 8080

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: smoke-test-analysis
spec:
  metrics:
    - name: smoke-test-analysis
      successCondition: result == "200"
      provider:
        web:
          url: https://c79f-144-212-5-9.ngrok-free.app/smoke_test
          method: GET
