apiVersion: v1
data:
  template.prod-webhook-template: |
    webhook:
      prod-webhook:
        method: POST
        body: |
          {
            "message": "Rollout Succeeded",
            "app": "{{app.metadata.name}}"
          }
  trigger.on-rollout-completed: |
    - send: [prod-webhook-template]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"template.prod-webhook-template":"webhook:\n  prod-webhook:\n    method: POST\n    body: |\n      {\n        \"message\": \"Rollout Succeeded\",\n        \"app\": \"{{app.metadata.name}}\"\n      }\n","trigger.on-rollout-completed":"- send: [prod-webhook-template]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"argo-rollouts-notification-configmap","namespace":"argocd"}}
  creationTimestamp: "2025-02-06T14:50:02Z"
  name: argo-rollouts-notification-configmap
  namespace: argocd
  resourceVersion: "242433"
  uid: ab469c8b-c76f-48e4-a1ba-6a41d90e635b
