apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-test-app-jlp
  namespace: default
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.prod-webhook: ""
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: smoke-test-analysis
      - setWeight: 50
      - pause: {duration: 30s}
  selector:
    matchLabels:
      app: go-test-app-jlp
  template:
    metadata:
      labels:
        app: go-test-app-jlp
    spec:
      containers:
      - name: go-test-app-jlp
        image: jbavuluri/go-test-app:2.6
        ports:
        - containerPort: 8080

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: smoke-test-analysis
spec:
  metrics:
    - name: smoke-test-analysis
      successCondition: result == "200"
      provider:
        web:
          url: https://c79f-144-212-5-9.ngrok-free.app/smoke_test
          method: GET

