apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolboxes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jahnavibavuluri/go-test-app.git'
    targetRevision: HEAD
    path: minikube
  destination:
    server: 'https://192.168.49.2:8443'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
